FlyNetworks:
  Google:
    Closure:
      DependencyBuilder:
        Default:
          OutputFileName: 'Deps.js'
      Compiler:
        Default:
          Id: 'flynetworks-google-closure'
          ClosureLibrary: 'resource://FlyNetworks.Google.Closure/Public/closure/goog'
          OutputWrapper: ''
          Mode: 'ADVANCED'
          Level: 'VERBOSE'
          Paths: []
          Externs: []
          Modules: []
          Define:
            goog.DEBUG: false