FlyNetworks:
  Google:
    Closure:
      CompileCommand: 'java -jar %FLOW_PATH_ROOT%Packages/Application/FlyNetworks.Google.Closure/Resources/Private/Bin/Plovr.jar build'
      DependencyBuilderCommand: 'python %FLOW_PATH_ROOT%Packages/Application/FlyNetworks.Google.Closure/Resources/Public/closure/bin/build/depswriter.py'
      EmbedScriptMode: 'compiled'
      DependencyBuilder:
        Default:
          OutputFileName: 'Deps.js'
      Compiler:
        Default:
          Id: 'flynetworks-google-closure'
          ClosureLibrary: 'resource://FlyNetworks.Google.Closure/Public/closure/goog'
          OutputWrapper: ''
          Mode: 'ADVANCED'
          Level: 'VERBOSE'
          Paths: []
          Externs: []
          Modules: []
          Define:
            goog.DEBUG: false